// This file is auto-generated by @hey-api/openapi-ts


export type BodyTokenApiV1AuthTokenPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type CreateUser = {
    username: string;
    password: string;
};

export type User = {
    id: string
    is_active?: boolean
    is_admin?: boolean
    username?: string | null
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};


export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type WelcomeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type WelcomeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TokenApiV1AuthTokenPostData = {
    body: BodyTokenApiV1AuthTokenPost;
    path?: never;
    query?: never;
    url?: '/api/v1/auth/token';
};

export type TokenApiV1AuthTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TokenApiV1AuthTokenPostError = TokenApiV1AuthTokenPostErrors[keyof TokenApiV1AuthTokenPostErrors];

export type TokenApiV1AuthTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type TokenApiV1AuthTokenPostResponse = TokenApiV1AuthTokenPostResponses[keyof TokenApiV1AuthTokenPostResponses];

export type CreateUserApiV1AuthRegisterPostData = {
    body: CreateUser;
    path?: never;
    query?: never;
    url?: '/api/v1/auth/register';
};

export type CreateUserApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1AuthRegisterPostError = CreateUserApiV1AuthRegisterPostErrors[keyof CreateUserApiV1AuthRegisterPostErrors];

export type CreateUserApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type ReadCurrentUserApiV1AuthReadCurrentUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url?: '/api/v1/auth/read_current_user';
};

export type ReadCurrentUserApiV1AuthReadCurrentUserGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllUsersApiV1AuthReadAllUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/read_all_users';
};

export type GetAllUsersApiV1AuthReadAllUsersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TestingApiV1AuthMeUsernameGetData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/api/v1/auth/me/{username}';
};

export type TestingApiV1AuthMeUsernameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestingApiV1AuthMeUsernameGetError = TestingApiV1AuthMeUsernameGetErrors[keyof TestingApiV1AuthMeUsernameGetErrors];

export type TestingApiV1AuthMeUsernameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type IndexApiV1ChartsHostGetData = {
    body?: never;
    path: {
        host: unknown;
    };
    query?: never;
    url: '/api/v1/charts/{host}';
};

export type IndexApiV1ChartsHostGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IndexApiV1ChartsHostGetError = IndexApiV1ChartsHostGetErrors[keyof IndexApiV1ChartsHostGetErrors];

export type IndexApiV1ChartsHostGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChartDataApiV1ChartsHostChartDataGetData = {
    body?: never;
    path: {
        host: unknown;
    };
    query?: never;
    url: '/api/v1/charts/{host}/chart-data';
};

export type ChartDataApiV1ChartsHostChartDataGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChartDataApiV1ChartsHostChartDataGetError = ChartDataApiV1ChartsHostChartDataGetErrors[keyof ChartDataApiV1ChartsHostChartDataGetErrors];

export type ChartDataApiV1ChartsHostChartDataGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiV1LoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login';
};

export type LoginApiV1LoginGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProfileApiV1ProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profile';
};

export type ProfileApiV1ProfileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProfileApiV1DashboardGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard';
};

export type ProfileApiV1DashboardGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};