/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as LoginImport } from './routes/login';
import { Route as LayoutImport } from './routes/_layout';
import { Route as LayoutIndexImport } from './routes/_layout/index';
// Create/Update Routes
const LoginRoute = LoginImport.update({
    path: '/login',
    getParentRoute: () => rootRoute,
});
const LayoutRoute = LayoutImport.update({
    id: '/_layout',
    getParentRoute: () => rootRoute,
});
const LayoutIndexRoute = LayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutRoute,
});
// Create and export the route tree
export const routeTree = rootRoute.addChildren([
    LayoutRoute.addChildren([
        LayoutIndexRoute,
    ]),
    LoginRoute,
]);
/* prettier-ignore-end */ 
