"""Add hosts models

Revision ID: 5e791ee0d3d9
Revises: 996fe8c1d0f9
Create Date: 2025-04-27 17:33:25.931413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e791ee0d3d9'
down_revision: Union[str, None] = '996fe8c1d0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
